DrivingSchoolManagement/DrivingSchoolManagement/Controllers/LessonsController.cs
using DrivingSchoolDb;
using DrivingSchoolManagement.Models;
using DrivingSchoolManagement.Services;
using DrivingSchoolManagement.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrivingSchoolManagement.Controllers
{
    public class LessonsController : Controller
    {
        DrivingSchoolManagementEntities db = new DrivingSchoolManagementEntities();

        [DSMAuthorize("User")]
        public ActionResult Index()
        {
            Session["LessonDate"] = null;
            return View();
        }

        public ActionResult SaveLessonDateInSession(DateTime lessonDate)
        {
            Session["LessonDate"] = lessonDate.ToShortDateString();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LessonCreateFormLayout()
        {
            var studentId = (int)Session["UserID"];
            var model = new LessonCreateViewModel();
            var driver = db.StudentInfoes.FirstOrDefault(x => x.StudentID == studentId).DriverInfo.User;

            var student = db.Users.FirstOrDefault(x => x.UserID == studentId);

            model.Student = $"{student.FirstName} {student.LastName}";
            model.Driver = $"{driver.FirstName} {driver.LastName}";

            return PartialView("_lessonCreateFormLayout", model);
        }

        public ActionResult SaveLessonInDB(LessonCreateViewModel item)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var driver = db.Users.FirstOrDefault(x => x.FirstName + " " + x.LastName == item.Driver);
                    var student = db.Users.FirstOrDefault(x => x.FirstName + " " + x.LastName == item.Student);
                    var lessonDate = DateTime.Parse((string)Session["LessonDate"]);
                    var newLesson = new Lesson()
                    {
                        DateCreated = DateTime.Now,
                        DriverID = driver.UserID,
                        StudentID = student.UserID,
                        LessonDate = lessonDate,
                        LessonTimeID = item.LessonTimeID
                    };

                    db.Lessons.Add(newLesson);
                    db.SaveChanges();
                }
                catch (Exception e)
                {

                }
            }
            return RedirectToAction("Index");
        }

        [DSMAuthorize("User")]
        public ActionResult MyLessons()
        {
            return PartialView();
        }

        public ActionResult ActualLessonsGridViewPartial()
        {
            var model = new List<MyLessonsViewModel>();
            var userId = (int)Session["UserID"];
            List<Lesson> myLessons;

            if (DrivingSchoolDataProvider.IsUserStudent(userId))
                myLessons = db.Lessons.Where(x => x.StudentID == userId).ToList();
            else
                myLessons = db.Lessons.Where(x => x.DriverID == userId).ToList();

            foreach (var lesson in myLessons)
            {
                if (DrivingSchoolDataProvider.GetLessonDateTime(lesson) > DateTime.Now)
                    model.Add(new MyLessonsViewModel(lesson));
            }

            return PartialView("_actualLessonsGridViewPartial", model);
        }

        public ActionResult HistoryLessonsGridViewPartial()
        {
            var model = new List<MyLessonsViewModel>();
            var userId = (int)Session["UserID"];
            List<Lesson> myLessons;

            if (DrivingSchoolDataProvider.IsUserStudent(userId))
                myLessons = db.Lessons.Where(x => x.StudentID == userId).ToList();
            else
                myLessons = db.Lessons.Where(x => x.DriverID == userId).ToList();

            foreach (var lesson in myLessons)
            {
                if (DrivingSchoolDataProvider.GetLessonDateTime(lesson) < DateTime.Now)
                    model.Add(new MyLessonsViewModel(lesson));
            }

            return PartialView("_historyLessonsGridViewPartial", model);
        }

        public void CancelLesson(int lessonId)
        {
            var deleteLesson = db.Lessons.FirstOrDefault(x => x.LessonID == lessonId);

            db.Lessons.Remove(deleteLesson);
            db.SaveChanges();
        }


    }
}

DrivingSchoolManagement/DrivingSchoolManagement/Views/Shared/ContentLeftPartialView.cshtml
@using System.Drawing
<div class="leftPanel">
    @Html.DevExpress().NavBar(settings =>
{
    settings.Name = "LeftNavBar";
    settings.AutoCollapse = false;
    settings.EnableAnimation = false;
    settings.AllowExpanding = false;
    settings.Width = System.Web.UI.WebControls.Unit.Pixel(150);
    settings.Styles.GroupContent.BackColor = Color.Transparent;
    settings.Styles.GroupHeaderCollapsed.BackColor = Color.Transparent;
    settings.Styles.Item.HoverStyle.BackColor = Color.FromArgb(76, 163, 223);
    settings.Styles.Item.HoverStyle.ForeColor = Color.White;
    settings.Styles.Item.SelectedStyle.BackColor = Color.FromArgb(76, 163, 223);
    settings.Styles.Item.SelectedStyle.ForeColor = Color.White;

    settings.Styles.GroupContent.Border.BorderStyle = BorderStyle.None;
    settings.Styles.GroupHeader.Border.BorderStyle = BorderStyle.None;
    settings.Styles.GroupHeaderCollapsed.Border.BorderStyle = BorderStyle.None;


    settings.Groups.Add(group =>
    {
        group.Text = "Konto";
        group.Items.Add(item =>
        {
            item.Selected = true;
            item.Text = "Moje dane";
            item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Account", Action = "Index" });
        });
        group.Items.Add(item =>
        {
            item.Text = "Zmień hasło";
            item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Account", Action = "Password" });
        });
    });

}).GetHtml()
</div>

DrivingSchoolManagement/DrivingSchoolManagement/Views/Shared/HeaderPartialView.cshtml
@using DrivingSchoolManagement.Models;
@model HeaderViewRenderMode
<style>
    #HeaderMenu_DXI0_T span, #HeaderMenu_DXI1_T span, #HeaderMenu_DXI2_T span, #HeaderMenu_DXI3_T span, #HeaderMenu_DXI4_T span, #HeaderMenu_DXI5_T span {
        margin-top: -10px !important;
    }

    .tooltip .tooltiptext {
        visibility: hidden;
        width: 160px;
        background-color: #0966b1;
        color: #fff;
        text-align: center;
        border-radius: 6px;
        padding: 5px 5px;
        position: absolute;
        z-index: 1;
        top: 6px;
        left: 125px;
    }

    .tooltip:hover .tooltiptext{
        visibility:visible;
    }
</style>
<script>
    function LogoutButton() {
        var url = '@Url.Action("Logout", "Home")';
        window.location.href = url;
    }
</script>
@if (Model == HeaderViewRenderMode.Title)
{
    <div class="templateTitle">
        @Html.ActionLink("Home", "Index", "Home")
    </div>
}
else
{
    if (Model == HeaderViewRenderMode.Full)
    {
        <div class="headerTop">
            <div class="templateTitle" style="width:300px">
                <a href='@Url.Action("Index", "Home")'>
                    <img src='@Url.Content("~/Content/Images/kurs-L-samochodowy.jpg")' style="margin-top:2px;margin-left: 10px; width:50px; height:50px; float:left;" />
                </a>
                @if (Session["UserID"] != null)
                {
                    if (DrivingSchoolDataProvider.IsUserStudent((int)Session["UserID"]) && DrivingSchoolDataProvider.StudentHasIncomingLesson((int)Session["UserID"]))
                    {
                        <a href='@Url.Action("MyLessons", "Lessons")'>
                            <div class="tooltip"><img src='@Url.Content("~/Content/Images/alert.png")' style="float:left; width:35px; margin-left:25px; margin-top:10px;" />
                                <span class="tooltiptext">Następna nauka jazdy za mniej niż 12h!</span>
                            </div>
                            
                        </a>
                    }

                } 
            </div>
        @if (HttpContext.Current.Session["UserID"] != null)
        {
            <div class="logoutButton" style="float:right; margin-top: 12px; margin-right: 10px">
                @Html.DevExpress().Button(bt =>
                    {
                        bt.Text = "Wyloguj się";
                        bt.Name = "LogoutButton";
                        bt.ClientSideEvents.Click = "LogoutButton";
                    }).GetHtml()
            </div>
            <div class="userChip" style="float: right;margin-right: 20px;margin-top: 4px;">
            
                    <img src="~/Content/Images/icons8-customer-48.png" alt="User Name" style="vertical-align: middle; height: inherit;">
                    <span style="color:white">@DrivingSchoolManagement.Models.DrivingSchoolDataProvider.GetUserNameById((int)(Session["UserID"]))</span>
            </div>   
        }
        </div>
    }

    <div class="headerMenu" style="float: left; margin-left: 20px; display: flex">
        @Html.DevExpress().Menu(settings =>
   {
       settings.Name = "HeaderMenu";
       settings.ItemAutoWidth = false;
       settings.Width = Unit.Percentage(100);
       settings.AllowSelectItem = true;
       if (Session["UserID"] != null)
       {
           settings.Items.Add(item =>
           {
               item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Home" });
               item.Text = "Strona główna";
           });
           if (!DrivingSchoolDataProvider.IsUserManager((int)Session["UserID"]))
           {
               settings.Items.Add(item =>
               {
                   item.NavigateUrl =  DrivingSchoolDataProvider.IsUserStudent((int)Session["UserID"]) ?
                                       DevExpressHelper.GetUrl(new { Controller = "Lessons" }) :
                                       DevExpressHelper.GetUrl(new { Controller = "Lessons", Action = "MyLessons" });
                   item.Text = "Spotkania";
               });
           }
           settings.Items.Add(item =>
           {
               item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Drivers" });
               item.Text = "Instruktorzy";
           });
           settings.Items.Add(item =>
           {
               item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Managers" });
               item.Text = "Menadżerowie";
           });
           settings.Items.Add(item =>
           {
               item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Vehicles" });
               item.Text = "Pojazdy";
           });
           settings.Items.Add(item =>
           {
               item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Account" });
               item.Text = "Moje konto";
           });
           if (DrivingSchoolDataProvider.IsUserManager((int)Session["UserID"])){
               settings.Items.Add(item =>
               {
                   item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = "Admin", Action = "Index" });
                   item.Text = "Panel administracyjny";
               });
           }


       }
   }).GetHtml()
    </div>
}

DrivingSchoolManagement/DrivingSchoolManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8" />
    <title>DevExpress ASP.NET project</title>
    
    @Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new StyleSheet { ExtensionSuite = ExtensionSuite.CardView },
        new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
        new StyleSheet { ExtensionSuite = ExtensionSuite.SpellChecker },
        new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new StyleSheet { ExtensionSuite = ExtensionSuite.RichEdit },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
        new StyleSheet { ExtensionSuite = ExtensionSuite.VerticalGrid },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
        new StyleSheet { ExtensionSuite = ExtensionSuite.QueryBuilder },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView },
        new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Dashboard }
    )
    @Html.DevExpress().GetScripts( 
        new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new Script { ExtensionSuite = ExtensionSuite.CardView },
        new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
        new Script { ExtensionSuite = ExtensionSuite.SpellChecker },
        new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new Script { ExtensionSuite = ExtensionSuite.RichEdit },
        new Script { ExtensionSuite = ExtensionSuite.Editors },
        new Script { ExtensionSuite = ExtensionSuite.VerticalGrid },
        new Script { ExtensionSuite = ExtensionSuite.Spreadsheet },
        new Script { ExtensionSuite = ExtensionSuite.Scheduler },
        new Script { ExtensionSuite = ExtensionSuite.Chart },
        new Script { ExtensionSuite = ExtensionSuite.Report },
        new Script { ExtensionSuite = ExtensionSuite.QueryBuilder },
        new Script { ExtensionSuite = ExtensionSuite.GridView },
        new Script { ExtensionSuite = ExtensionSuite.TreeList },
        new Script { ExtensionSuite = ExtensionSuite.Dashboard }
    )
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="content-wrapper">
        <div class="header">
            <h1>DevExpress ASP.NET project</h1>
            @Html.DevExpress().Menu(settings => {
                settings.Name = "HeaderMenu";
                settings.ItemAutoWidth = false;
                settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
                settings.Styles.Style.Border.BorderWidth = System.Web.UI.WebControls.Unit.Pixel(0);
                settings.Styles.Style.Paddings.Padding = System.Web.UI.WebControls.Unit.Pixel(0);
                settings.Items.Add("Home");
                settings.Items.Add("About");
                settings.Items.Add("Contact");
            }).GetHtml()
        </div>

        <div class="content">
            @RenderBody()
        </div>

        <div class="footer">
            <p>&copy; @DateTime.Now.Year - DevExpress ASP.NET project copyright</p>
        </div>
    </div>
</body>
</html>

DrivingSchoolManagement/DrivingSchoolManagement/Views/Shared/_rootLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, maximum-scale=1.0, minimum-scale=1.0" />
    <title>@ViewBag.Title - Ośrodek Szkolenia Kierowców</title>
    
    @Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
        new StyleSheet { ExtensionSuite = ExtensionSuite.VerticalGrid },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Spreadsheet },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }
    )
    @Html.DevExpress().GetScripts( 
        new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new Script { ExtensionSuite = ExtensionSuite.Editors },
        new Script { ExtensionSuite = ExtensionSuite.VerticalGrid },
        new Script { ExtensionSuite = ExtensionSuite.Spreadsheet },
        new Script { ExtensionSuite = ExtensionSuite.Chart },
        new Script { ExtensionSuite = ExtensionSuite.GridView }
    )
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

</head>

<body>
    @Html.DevExpress().Panel(settings => {
        settings.Name = "HeaderPane";
        settings.FixedPosition = PanelFixedPosition.WindowTop;
        settings.Collapsible = true;
        settings.SettingsAdaptivity.CollapseAtWindowInnerWidth = 500;
        settings.ControlStyle.CssClass = "headerPane";
        settings.Styles.Panel.CssClass = "panel";
        settings.Styles.ExpandedPanel.CssClass = "expandedPanel";
        settings.Styles.ExpandBar.CssClass = "bar";
        settings.SetContent(() => {
            Html.RenderPartial("HeaderPartialView", HeaderViewRenderMode.Full);
        });
        settings.SetExpandBarTemplateContent((c) => {
            Html.RenderPartial("HeaderPartialView", HeaderViewRenderMode.Title);
        });
    }).GetHtml()

    <script type="text/javascript">
        function updateHeaderMenuOrientation(){
            if(!window.HeaderMenu) return;
            var orientation = HeaderPane.IsExpandable() ? 'Vertical' : 'Horizontal';
            if(orientation !== HeaderMenu.GetOrientation())
                HeaderMenu.SetOrientation(orientation);
        }
        var collection = ASPxClientControl.GetControlCollection();
        collection.ControlsInitialized.AddHandler(updateHeaderMenuOrientation);
        collection.BrowserWindowResized.AddHandler(updateHeaderMenuOrientation);
    </script>

    @Html.DevExpress().Panel(settings => {
        settings.Name = "MainPane";
        settings.ControlStyle.CssClass = "mainContentPane";
        settings.SetContent(RenderBody().ToHtmlString());
    }).GetHtml()
</body>
</html>

DrivingSchoolManagement/DrivingSchoolManagement/Views/Shared/_userExtraDataFormPartial.cshtml
@using DrivingSchoolManagement.ViewModels
@using System.Drawing
@using DrivingSchoolManagement.Models
@model AccountDetailsViewModel

@Html.DevExpress().FormLayout(fl =>
{
    fl.Width = Unit.Percentage(50);
    fl.Style.Add("margin", "0 auto");
    fl.Name = "AccountDetailsFormLayout";
    fl.EncodeHtml = false;
    var firstGroupItem = fl.Items.AddGroupItem(i =>
    {
        i.Caption = "Dodatkowe dane użytkownika";
        i.SettingsItemHelpTexts.Position = HelpTextPosition.Bottom;
    });
    firstGroupItem.Items.Add(m => m.PESEL, i =>
    {
        i.Caption = "PESEL";
        i.NestedExtension().TextBox(s =>
        {
            s.Width = Unit.Percentage(100);
            s.ReadOnly = true;
        });
    });
    firstGroupItem.Items.Add(m => m.DateCreated, i =>
    {
        i.Caption = "Data utworzenia";
        i.NestedExtension().DateEdit(s =>
        {
            s.Width = Unit.Percentage(100);
            s.ReadOnly = true;
            s.Properties.EditFormat = EditFormat.Custom;
            s.Properties.EditFormatString = "dd MMMM yyyy";
        });
    });

    var secondGroupItem = fl.Items.AddGroupItem(i =>
    {
        i.Caption = "Adres";
        i.SettingsItemHelpTexts.Position = HelpTextPosition.Bottom;
    });

    secondGroupItem.Items.Add(m => m.StreetName, i =>
    {
        i.Caption = "Ulica";
        i.NestedExtension().TextBox(s =>
        {
            s.Width = Unit.Percentage(100);
            s.ReadOnly = true;
        });
    });
    secondGroupItem.Items.Add(m => m.Number, i =>
    {
        i.Caption = "Numer domu";
        i.NestedExtension().TextBox(s =>
        {
            s.Width = Unit.Percentage(100);
            s.ReadOnly = true;
        });
    });
    secondGroupItem.Items.Add(m => m.PostalCode, i =>
    {
        i.Caption = "Kod pocztowy";
        i.NestedExtension().TextBox(s =>
        {
            s.Width = Unit.Percentage(100);
            s.ReadOnly = true;
        });
    });
    secondGroupItem.Items.Add(m => m.City, i =>
    {
        i.Caption = "Miejscowość";
        i.NestedExtension().TextBox(s =>
        {
            s.Width = Unit.Percentage(100);
            s.ReadOnly = true;
        });
    });
    secondGroupItem.Items.Add(m => m.Country, i =>
    {
        i.Caption = "Państwo";
        i.NestedExtension().TextBox(s =>
        {
            s.Width = Unit.Percentage(100);
            s.ReadOnly = true;
        });
    });

}).Bind(Model).GetHtml();